version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=localhost
    depends_on:
      - redis

  redis:
    image: "redis:alpine"